from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping

import pandas as pd

"""TradeSide
    What it does: Defines the direction of a trade.

    BUY: Buy order.
    SELL: Sell order.
	
	---
    BacktestConfig
    What it does: Stores all configurable parameters used by the backtesting engine, 
	such as initial capital, rebalancing frequency, transaction costs, and trading rules.

	---
    Order
    What it does: Represents a target portfolio order generated by the strategy before execution.

	---
    Position
    What it does: Represents a portfolio holding, including the number of shares owned 
	and the latest market price.

    Property:
        market_value
        What it does: Calculates the current market value of the position.
        
        Output
        Returns quantity × last_price (float).

	---	
    PortfolioState
    What it does: Represents an immutable snapshot of the portfolio used by strategies 
	during backtesting.

	---
    TradeRecord
    What it does: Stores the details of an executed trade, including execution price, 
	quantity, transaction cost, and target weight.

	---
    HistoryRow
    What it does: Represents the portfolio's state and performance for a single trading day.

	---
    DailySnapshot
    What it does: Alias for HistoryRow, representing a single daily portfolio snapshot.

	---
    BacktestResult
    What it does: Stores the complete results of a backtest, including the configuration, 
	portfolio history, and executed trades.

    Property:
    final_value
        What it does: Returns the final portfolio value after the backtest.
        
        Output
        Returns the final portfolio value (float), or the initial cash if no history exists.
"""

class TradeSide(str, Enum):
	BUY = "buy"
	SELL = "sell"


@dataclass(frozen=True)
class BacktestConfig:
	initial_cash: float = 100000.0
	rebalance_frequency: int = 1
	transaction_cost_bps: float = 5.0
	annualization_factor: int = 252
	whole_shares: bool = True
	max_position_count: int | None = None
	starting_price: float = 100.0


@dataclass(frozen=True)
class Order:
	date: pd.Timestamp
	symbol: str
	target_weight: float


@dataclass(frozen=True)
class Position:
	quantity: float = 0.0
	last_price: float = 0.0

	@property
	def market_value(self) -> float:
		return self.quantity * self.last_price


@dataclass(frozen=True)
class PortfolioState:
	cash: float
	positions: Mapping[str, Position] = field(default_factory=dict)
	total_value: float = 0.0


@dataclass(frozen=True)
class TradeRecord:
	date: pd.Timestamp
	symbol: str
	side: TradeSide
	quantity: float
	price: float
	notional: float
	cost: float
	target_weight: float


@dataclass(frozen=True)
class HistoryRow:
	date: pd.Timestamp
	portfolio_value: float
	cash: float
	gross_exposure: float
	net_exposure: float
	daily_return: float


DailySnapshot = HistoryRow


@dataclass(frozen=True)
class BacktestResult:
	config: BacktestConfig
	history: pd.DataFrame
	trades: pd.DataFrame = field(default_factory=pd.DataFrame)

	@property
	def final_value(self) -> float:
		if self.history.empty:
			return self.config.initial_cash
		return float(self.history.iloc[-1]["portfolio_value"])
